// Per ognuna delle 50: perche' ha superato il filtro di concorrenza gratuita,
// e l'esito del test a ritroso quando applicabile (formula verificata con
// calcolo indipendente in test-a-ritroso.js).
module.exports = {
1:  { conc:"Nessun diario di trading gratuito unisce Win-Rate, R-multiplo e stato emotivo in un'unica pivot.", test:"Win-rate e R media verificati su una serie di 7 trade di esempio: 4/7=57,1% e R media 0,643, entrambi confermati da calcolo indipendente." },
3:  { conc:"I backtester gratuiti (TradingView incluso) non producono un report con soglie di validazione pronte da leggere.", test:"Profit Factor (1,65) e Max Drawdown (120) verificati su una serie di 7 trade costruita a mano, calcolo indipendente confermato." },
13: { conc:"Le app fitness gratuite tracciano i carichi ma non applicano automaticamente la regola di progressione basata su RPE e range.", test:"Logica di incremento verificata: il carico sale solo se tutte le serie raggiungono il tetto del range di ripetizioni." },
14: { conc:"I generatori di tabelle maratona gratuiti non calcolano le zone di ritmo con la formula di Riegel a partire da un tempo recente.", test:"Formula di Riegel verificata con calcolo indipendente in Python (doppia precisione): 6619,21s, identico al risultato JS." },
15: { conc:"Le guide di fisioterapia sportiva online sono generiche; nessuna struttura per fasi con criteri di passaggio oggettivi (non date) e diario integrato.", test:"—" },
20: { conc:"Nessun tool gratuito calcola automaticamente orari e pause di una maratona di film a partire dalle durate reali.", test:"Durata totale con pause verificata: 3 film + 2 pause da 20 min = 400 minuti, calcolo indipendente confermato." },
21: { conc:"Le guide generiche sul noleggio non forniscono una sequenza di scatti ordinata con validità legale.", test:"—" },
23: { conc:"Nessun modello gratuito include verbale, foto, calcolo interessi legali E diffida nello stesso strumento (prodotto gia costruito e testato).", test:"Interessi legali 2023-2026 (127,15€) e limite delle 3 mensilità (1.800€) riverificati con calcolo indipendente, esito confermato." },
25: { conc:"I siti di recensioni segnalano il problema ma nessuno calcola il costo reale a notte con tutte le voci incluse.", test:"Costo reale a notte verificato: tariffa 60€ x3 notti + pulizie 40€ + comm. 14% + tassa soggiorno = 85,60€/notte, calcolo indipendente confermato." },
26: { conc:"I budget generici non usano il rapporto empirico affitto x1,6 né il fondo di partenza a 3 mensilità.", test:"Fabbisogno mensile (800€ su affitto 500€) e fondo di partenza (1.500€) verificati con calcolo indipendente." },
27: { conc:"Le guide di meal planning sono generiche; nessuna versione ottimizzata sul riciclo di 3 ingredienti condivisi su 5 cene.", test:"—" },
28: { conc:"I planner pulizie gratuiti non sono strutturati per chi lavora full time in micro-mansioni da 10 minuti.", test:"—" },
29: { conc:"Le guide dei singoli fornitori spiegano la propria procedura, non esiste un percorso unificato POD+PDR+residenza+TARI con moduli pronti.", test:"—" },
30: { conc:"I forum di bricolage rispondono caso per caso; nessuna guida strutturata sulle 20 emergenze più comuni con semaforo fai-da-te/chiama subito.", test:"—" },
31: { conc:"Le guide generiche 'cosa controllare' non sono personalizzate per marca/modello con i difetti noti di quel motore.", test:"—" },
32: { conc:"Nessuno strumento gratuito proietta i costi di manutenzione sui prossimi 30.000 km per il modello specifico.", test:"—" },
34: { conc:"Verificato esplicitamente: Eurotax non valuta auto danneggiate ('serve perizia in presenza'); nessun tool calcola la soglia riparare-vs-vendere.", test:"Regola di decisione verificata: danno 4.500€ su valore 4.000€ -> vendere; danno 2.000€ su valore 4.000€ -> riparare. Confermato." },
36: { conc:"Le mappe pet-friendly esistenti non verificano il limite di taglia reale né l'accesso libero in area recintata.", test:"—" },
38: { conc:"Prodotti commerciali (Thundershirt, Adaptil) risolvono il sintomo; nessun protocollo gratuito di desensibilizzazione progressiva calibrata.", test:"—" },
39: { conc:"Le guide sul ciclo dell'azoto sono divulgative; nessun calcolatore di compatibilità specie + volume prima dell'acquisto.", test:"—" },
40: { conc:"Le liste di piante/cibi tossici sono statiche; nessuna calcola la dose in base al peso dell'animale con numero del centro antiveleni in evidenza.", test:"—" },
44: { conc:"Le community camperisti condividono itinerari non verificati; nessun controllo automatico di vincoli altezza/massa sul percorso.", test:"—" },
51: { conc:"I template statici di sollecito esistono gratis, ma nessuno automatizza la sequenza a 3 stadi con interessi di mora calcolati.", test:"Formula ufficiale D.Lgs 231/2002 verificata con l'esempio pubblicato (fattura 10.000€, 90gg, tasso 10,15%) = 290,27€. Un primo tentativo di formula divideva per 100 due volte (risultato 42,50€, sbagliato di un fattore 100): bug trovato e corretto da questo test." },
54: { conc:"Nessun analizzatore gratuito è calibrato sulle clausole vessatorie del Codice del Consumo italiano con evidenziazione automatica.", test:"—" },
55: { conc:"AirHelp/ClaimCompass trattengono il 25-50% in caso di successo; un generatore DIY a costo fisso è un'alternativa reale.", test:"Fasce di compensazione EU261 (250/400/600€) verificate contro il testo del regolamento per tre distanze di esempio." },
57: { conc:"DeepL traduce alla lettera; nessuno spiega i piatti italiani con la logica richiesta dal turista straniero.", test:"—" },
59: { conc:"Lexica e PromptHero permettono solo la ricerca in una galleria esistente, non la composizione guidata di un prompt nuovo per un caso d'uso specifico.", test:"—" },
61: { conc:"Le guide sul sonno sono generiche; nessuna genera un programma orario personalizzato sul tipo di turno.", test:"—" },
66: { conc:"I calcolatori di liquidazione sono quasi tutti in inglese e generici; nessuno confronta isolato vs incrociato sullo stesso scenario in italiano.", test:"Formula di liquidazione long/short verificata: entry 100 con leva 10x long -> 90; leva 5x short -> 120. Calcolo indipendente confermato." },
68: { conc:"Nessuno strumento sottrae automaticamente spread e commissioni dal profitto teorico per lo scalping.", test:"Break-even in pip (spread 1,2 + commissione equiv. 0,8 = 2,0 pip) verificato con calcolo indipendente." },
69: { conc:"Gli indicatori TradingView segnalano il pattern ma non incrociano struttura+volume+timeframe superiore in un'unica regola meccanica.", test:"—" },
76: { conc:"I generatori di tabelloni gratuiti non gestiscono bene bye/orari per campi sportivi amatoriali con notifiche automatiche.", test:"Dimensione bracket e bye verificati: 11 partecipanti -> bracket 16 con 5 bye; 8 partecipanti -> bracket 8 con 0 bye. Confermato." },
80: { conc:"Le guide di nutrizione sportiva danno un range generico; nessuna genera un piano al chilometro personalizzato sul tempo di gara previsto.", test:"Fabbisogno di carboidrati per una gara di 4 ore verificato: tra 180g e 270g nelle 3 ore oltre la prima, calcolo indipendente confermato." },
81: { conc:"I tracker di saghe esistono per singoli franchise; nessuno copre più universi condivisi in una lista unica spuntabile.", test:"—" },
82: { conc:"Le app di votazione generiche non sono pensate per gruppi di amici/Discord con meccanismo di voto ad approvazione anonimo.", test:"Meccanismo di voto ad approvazione verificato su un caso di 5 elettori e 3 opzioni: vince l'opzione approvata da 4 elettori su 5, come atteso." },
83: { conc:"I calendari cinema generici non avvisano specificamente all'apertura delle prevendite dei film evento.", test:"—" },
84: { conc:"Verificato esplicitamente: MyAnimeList traccia i CAPITOLI LETTI ma non è pensato per catalogare i VOLUMI FISICI posseduti (fonte: MakeUseOf/Mihon docs). Gap reale.", test:"—" },
85: { conc:"Le spiegazioni sparse sui forum non seguono una struttura fissa letterale/tematico/alternative; prodotto strutturato e ripetibile.", test:"—" },
86: { conc:"Le guide generiche sul subaffitto non distinguono normativa comunale + modulo di autorizzazione in un pacchetto pronto.", test:"—" },
88: { conc:"Le guide sul noleggio nautico sono generiche; nessuna scheda di verifica fotografica pre-partenza standardizzata.", test:"Limite di potenza senza patente verificato: 30 kW x 1,36 = 40,8 CV, identico al valore normativo (art. 39 D.Lgs. 171/2005)." },
89: { conc:"Le guide sul car sharing spiegano le tariffe ma non calcolano il punto di pareggio minuti-vs-giornaliera per l'operatore scelto.", test:"Punto di pareggio verificato: tariffa giornaliera 59€ vs 0,19€/min -> pareggio a 310,5 minuti, calcolo indipendente confermato." },
90: { conc:"I modelli di diffida generici non sono specifici per guasti dell'immobile con riferimento agli obblighi del locatore.", test:"—" },
91: { conc:"Le guide di decluttering sono generiche; nessuna applica la regola dei 12 mesi con i 3 scatoloni in modo sistematico.", test:"—" },
92: { conc:"Splitwise gestisce spese generiche; nessuno strumento è calibrato sulla lista della spesa condivisa specifica dei coinquilini.", test:"—" },
93: { conc:"Le guide sul trasloco sono generiche; nessuna applica la numerazione sistematica scatola->stanza->contenuto con roadmap a 14 giorni.", test:"—" },
94: { conc:"Le guide sulle fasce orarie spiegano gli orari ma nessuna programma automaticamente gli elettrodomestici (verificato: nessuna app dedicata trovata).", test:"Copertura delle fasce F1+F2+F3 su una giornata feriale verificata: 11+5+8=24 ore, nessuna sovrapposizione né buco." },
96: { conc:"Le ricette online danno dosi per persona ma non applicano la correzione empirica oltre le 6 persone.", test:"Scaling dose verificato: 10 ospiti a 100g cad. con correzione -12,5% = 875g (non 1.000g lineari); sotto 6 ospiti nessuna correzione. Confermato." },
97: { conc:"Le guide sulla conservazione danno tempi generici; nessun tracker personalizzato con promemoria di scadenza per singolo alimento congelato.", test:"—" },
99: { conc:"Le guide sulla caldaia spiegano l'obbligo ma nessuno scadenzario automatico differenzia manutenzione annuale da controllo fumi biennale/quadriennale.", test:"—" },
100:{ conc:"I contenuti motivazionali generici non offrono una routine operativa con orizzonte temporale di 3 mesi per una nuova città.", test:"—" }
};
